### ISSUE TITLE
Create stddev : Standard deviation SQL Aggregate function

### ISSUE THREAD

**Issue by pamboo80** [rockset/tableau-connector#7]
Create SQL Aggregate function stddev in the backend/core.

**Comment by benhannel** [comment]
We already have `STDDEV_SAMP`. Do you want the population standard deviation?
https://docs.rockset.com/aggregate-functions/#stddev_samp

**Comment by tudor** [comment]
In PostgreSQL, `stddev` is an alias for `stddev_samp`, so I'll do the same.

**Comment by pamboo80** [comment]
> We already have `STDDEV_SAMP`. Do you want the population standard deviation?
> https://docs.rockset.com/aggregate-functions/#stddev_samp

STDDEV_SAMP will do. Thanks. I think we can close this issue.

**Comment by pamboo80** [comment]
With the help of STDDEV_SAMP and some updates in the dialects override, I can make the test cases pass for Standard deviation and Variance calculations required for Tableau. Already available STDDEV_SAMP is much enough as of now. So, closing this issue. Thanks.
